USE [master]
GO
/****** Object:  Database [internship]    Script Date: 7/5/2021 2:55:21 PM ******/
CREATE DATABASE [internship]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'internship', FILENAME = N'C:\Users\idiliev18\internship.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'internship_log', FILENAME = N'C:\Users\idiliev18\internship_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [internship] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [internship].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [internship] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [internship] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [internship] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [internship] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [internship] SET ARITHABORT OFF 
GO
ALTER DATABASE [internship] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [internship] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [internship] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [internship] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [internship] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [internship] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [internship] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [internship] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [internship] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [internship] SET  DISABLE_BROKER 
GO
ALTER DATABASE [internship] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [internship] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [internship] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [internship] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [internship] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [internship] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [internship] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [internship] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [internship] SET  MULTI_USER 
GO
ALTER DATABASE [internship] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [internship] SET DB_CHAINING OFF 
GO
ALTER DATABASE [internship] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [internship] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [internship] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [internship] SET QUERY_STORE = OFF
GO
USE [internship]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [internship]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 7/5/2021 2:55:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](64) NOT NULL,
	[Surname] [nvarchar](64) NULL,
	[LastName] [nvarchar](64) NOT NULL,
	[Gender] [nvarchar](12) NOT NULL,
	[Age] [tinyint] NOT NULL,
	[Position] [nvarchar](64) NOT NULL,
	[Salary] [smallint] NOT NULL,
	[YearOfAppointment] [smallint] NOT NULL,
	[TotalHolidays] [tinyint] NOT NULL,
	[UsedHolidays] [tinyint] NOT NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Employees]  WITH CHECK ADD  CONSTRAINT [CK_Age] CHECK  (([Age]>=(16)))
GO
ALTER TABLE [dbo].[Employees] CHECK CONSTRAINT [CK_Age]
GO
ALTER TABLE [dbo].[Employees]  WITH CHECK ADD  CONSTRAINT [CK_Gender] CHECK  (([Gender]='Male' OR [Gender]='Female' OR [Gender]='???' OR [Gender]='????'))
GO
ALTER TABLE [dbo].[Employees] CHECK CONSTRAINT [CK_Gender]
GO
ALTER TABLE [dbo].[Employees]  WITH CHECK ADD  CONSTRAINT [CK_Salary] CHECK  (([Salary]>=(650)))
GO
ALTER TABLE [dbo].[Employees] CHECK CONSTRAINT [CK_Salary]
GO
USE [master]
GO
ALTER DATABASE [internship] SET  READ_WRITE 
GO
